name: connect_flutter_plugin
description: Acoustic Connect can monitor traffic between your application and server. It captures device context and user activity to monitor and evaluate the performance of your applications
version: 2.36.6-beta
homepage: https://pub.dev/packages/connect_flutter_plugin
repository: https://github.com/acoustic-analytics/Connect-Flutter-Plugin
build-name: 2.36.6-beta
build-number: 2.36.6-beta
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.5.0'
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  http: ^1.0.0
  logger: ^2.0.0
  yaml: ^3.1.1
  package_info_plus: ^8.3.0
dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  mockito: ^5.4.4
  path: ^1.8.3
flutter:
  plugin:
    platforms:
      android:
        package: com.example.connect_flutter_plugin
        pluginClass: ConnectFlutterPlugin
      ios:
        pluginClass: ConnectFlutterPlugin
  assets:
  - pubspec.yaml
false_secrets:
- /example/gallery/android/app/google-services.json
- /example/gallery/ios/Runner/GoogleService-Info.plist
- /example/gallery/lib/firebase_options.dart
- /example/gallery/macos/Runner/GoogleService-Info.plist
- /example/gallery_app_clean/android/app/google-services.json
- /example/gallery_app_clean/ios/Runner/GoogleService-Info.plist
- /example/gallery_app_clean/lib/firebase_options.dart
- /example/gallery_app_clean/macos/Runner/GoogleService-Info.plist
